baseURL = "https://usrme.netlify.com/"
languageCode = "en-us"
title = "Ãœllar Seerme"
theme = "book"
PygmentsStyle = "monokailight"
[params]
BookMenuBundle = '/menu'
BookRepo = 'https://github.com/usrme/website'
